// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urebcpgszjtiingnecwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyZWJjcGdzemp0aWluZ25lY3dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjE3NzYsImV4cCI6MjA2NDUzNzc3Nn0.Q0BbaeJhoTo79suMYudYOcwz-3-oiSBA_IYoSg7vhSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);